/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6582. Copyright MediaTek Inc. (C) 2013.
<<<<<<< HEAD
 * Wed Nov 11 17:15:27 2015
=======
 * Tue Oct 20 17:09:11 2015
>>>>>>> origin/master
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


