/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6582. Copyright MediaTek Inc. (C) 2013.
<<<<<<< HEAD
 * Wed Nov 11 17:15:27 2015
=======
 * Tue Oct 20 17:09:11 2015
>>>>>>> origin/master
 * Do Not Modify the File.
 */



#include <linux/types.h>
#include <mach/mt_typedefs.h>
#include <mach/mt_pm_ldo.h>
void pmu_drv_tool_customization_init(void)
{
}


